// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Du2KpY5lSptpB0kI1E9vh1DlL2qoMwY',
    appId: '1:884369139876:web:fcf820093922b195509e31',
    messagingSenderId: '884369139876',
    projectId: 'task-intern-1cefe',
    authDomain: 'task-intern-1cefe.firebaseapp.com',
    databaseURL: 'https://task-intern-1cefe-default-rtdb.firebaseio.com',
    storageBucket: 'task-intern-1cefe.appspot.com',
    measurementId: 'G-DX2Z645X08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDETQNFmkgvEk9jsiq94zsvrS2MnpzSnYA',
    appId: '1:884369139876:android:9243a4c275cf3f72509e31',
    messagingSenderId: '884369139876',
    projectId: 'task-intern-1cefe',
    databaseURL: 'https://task-intern-1cefe-default-rtdb.firebaseio.com',
    storageBucket: 'task-intern-1cefe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYQ_wVP1_vV2QiCVPxmWDyLI9Ji2bnkAQ',
    appId: '1:884369139876:ios:9ece5c0b5e30d5c3509e31',
    messagingSenderId: '884369139876',
    projectId: 'task-intern-1cefe',
    databaseURL: 'https://task-intern-1cefe-default-rtdb.firebaseio.com',
    storageBucket: 'task-intern-1cefe.appspot.com',
    iosClientId: '884369139876-m8ie1t8d63b8itn74fhpq4anljm6ldr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskInternApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYQ_wVP1_vV2QiCVPxmWDyLI9Ji2bnkAQ',
    appId: '1:884369139876:ios:9ece5c0b5e30d5c3509e31',
    messagingSenderId: '884369139876',
    projectId: 'task-intern-1cefe',
    databaseURL: 'https://task-intern-1cefe-default-rtdb.firebaseio.com',
    storageBucket: 'task-intern-1cefe.appspot.com',
    iosClientId: '884369139876-m8ie1t8d63b8itn74fhpq4anljm6ldr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskInternApp',
  );
}
